Patch Endpoint
PJATK-SPK/ingoodhands pull request #40
Opened 2023-01-30 21:58 UTC by badekk

Create new endpoint to patch user details

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this been tested?

- [ ] Unit test(s)
- [X] Integration test(s)
- [X] Tested manually

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I have checked my code and corrected any misspellings
- [X] I have added frontend code and checked it for mobile & desktop

2023-01-30 21:58 UTC, mar-pan commented
Task linked: [CU-862hy9urf PATCH endpoint](https://app.clickup.com/t/862hy9urf)

2023-01-30 22:11 UTC, h4570 requested changes
Ładnie ci poszło

2023-01-30 22:11 UTC, h4570 commented on src/backend/AuthService/BusinessLogic/PatchUserDetails/PatchUserDetailsService.cs
> +        public async Task<bool> PatchUserFirstNameAndLastName(PatchUserDetailsPayload userSettingsPayload, long id)
`Task<bool>` na `Task` - poza tym gra. 🎆

2023-01-30 22:11 UTC, h4570 commented on src/backend/AuthService/BusinessLogic/PatchUserDetails/PatchUserDetailsAction.cs
> +            if (!patchUserDetailsPayloadIsValid)
Taka opcjonalna zmiana.
Jest drugie podejście do czegoś takiego, w którym możesz przenieść tego ifa wraz z zawartością do `ValidationService`. Wtedy tutaj się trochę odchudzi i `ValidationService.Check()` zamiast zwracać `bool`, będzie mógł być void.

2023-01-30 22:16 UTC, h4570 commented on src/backend/AuthService/BusinessLogic/PatchUserDetails/PatchUserDetailsPayloadDataValidationService.cs
> +            var check = userDetailsPayload.FirstName != null;
A jeszcze mi wpadło do głowy. 
Zwaliduj tutaj, czy `FirstName` i `LastName` ma długość `<=` niż pole z bazy. Rzuć tu wyjątkiem jak będzie źle.

2023-01-31 14:39 UTC, h4570 approved these changes

2023-02-01 11:38 UTC, merged